export const REQUIRE_NAME = "Name is required";
export const REQUIRE_EMAIL = "Email is required";
export const REQUIRE_TIME_END = "Time End is required";
export const REQUIRE_TIME_START = "Time Start is required";
export const REQUIRE_NOTE = "Note is required";
export const TIME_START_LESS_TIME_END = "Start time must be less than end time";
export const INVALID_EMAIL = "Invalid email address";
export const REQUIRE_PASSWORD = "Password is required";
export const PASSWORD_NOT_MATCH = "Confirm password not match";
