export const REQUIRE_NAME = "Họ và tên là bắt buộc";
export const REQUIRE_EMAIL = "Email là bắt buộc";
export const REQUIRE_TIME_END = "Thời gian kết thúc là bắt buộc";
export const REQUIRE_TIME_START = "Thời gian bắt đầu là bắt buộc";
export const REQUIRE_NOTE = "Ghi chú là bắt buộc";
export const TIME_START_LESS_TIME_END = "Thời gian bắt đầu phải nhỏ hơn thời gian kết thúc";
export const INVALID_EMAIL = "Địa chỉ email không hợp lệ";
export const REQUIRE_PASSWORD = "Mật khẩu là bắt buộc";
export const PASSWORD_NOT_MATCH = "Xác nhận mật khẩu không khớp";
